### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by bluebore** [baidu/bfs#102]
1. [x] Logging.h按时间&大小切log
   Logging.h switch file when the file reach a size limit
2. [ ] 多盘负载均衡
   Load balance between disks
3. [x] 异构机器调度
   Load balance between different server type(disk number, etc)
4. [ ] 机架感知
   rack recognize
5. [x] master热备
   Master HA
6. [x] chunkserver停机dump数据
   chunk server should close opened files before shutdown
7. [x] sdk端sync支持超时
   sdk support sync timeout
8. [ ] 副本恢复与gc逻辑使用后台扫描触发
   background gc and replica recover strategy
9. [x] SDK里File结构的生命周期管理
   Managing file cycle for files in sdk
10. [x] 统一SDK里两个CloseFile逻辑
    There are tow CloseFile in SDK.
11. [ ] webservice实现剥离出nameserver_impl
    Separate web service from Nameserver_impl
12. [x] 错误码，人性化报错
    Make error code readable
13. [x] 读写文件优先选择Client本地副本
    Read/write local copy first

**Comment by yvxiang** [comment]
异构机器调度　是啥，AddBlock时考虑机器的不同性能？

**Comment by bluebore** [comment]
对，磁盘大小、读写性能不一样

**Comment by yvxiang** [comment]
"读写文件优先选择Client本地副本"　是说根据client与cs之间的距离吗？（比如IP）

**Comment by bluebore** [comment]
对，现在发现即使在万兆网卡环境下，bfs也能把网卡占满
如果能让一个副本放在本地，能降低网卡1/3的负担

**Comment by yvxiang** [comment]
那这个副本什么时候删呢

**Comment by bluebore** [comment]
这个只是不同的3副本之一，不需要额外删除
AddBlock选chunkserver的时候，优先选择和Client的ip一样的cs
SDK读的时候，也优先选择和自己IP一样的cs去读

**Comment by yvxiang** [comment]
client那台机器上有cs的概率会很大？

**Comment by bluebore** [comment]
几乎100%
bfs的目标是管理数据中心中所有的磁盘，所以每台机器上都会有cs

**Comment by yvxiang** [comment]
这个列表里的内容，有更明确的要求，以及分工吗？

**Comment by bluebore** [comment]
可以有。。。
等我先搞个0.1版出来

**Comment by lfrdreamman** [comment]
嘿嘿，我也加入吧

**Comment by lylei** [comment]
#613
