### ISSUE TITLE
PullBlock区分优先级

### ISSUE THREAD

**Issue by bluebore** [baidu/bfs#201]
当前chunkserver接到pullblock的任务后，就丢到线程池里，在系统整体负载较高时，线程池消化任务速度很慢，导致后来的hi级别的recover任务排队很久。
由于系统负载是波动的，这里不能简单的由nameserver用并发控制，同样是1G的文件，在系统负载低的时候chunkserver可以在3秒钟内完成，但系统负载高的时候可能需要3分钟。

**Comment by yvxiang** [comment]
有没有必要单独限制cs pick的hi级别的recover任务数目？毕竟单个cs的能力还是有限的

**Comment by bluebore** [comment]
有，但没想好怎么限制。
是一个cs只能pick10个这种限制？如果是这样的话，那10个之外还给lo的么？如果给的话可能出现它recover完这10个hi的，就去recover lo的了，而还剩下很多hi的不会被pick

**Comment by bluebore** [comment]
我觉得这个应该结合当前负载计算一个值，另外还要参考hi_recover的总数，比如现在hi待pick的总数很高，就不用限制单个cs pick的量，如果总数很低，就大家平均下，每人少拿几个。。。

**Comment by yvxiang** [comment]
#212
