### ISSUE TITLE
Sdk错误类型整理

### ISSUE THREAD

**Issue by yvxiang** [baidu/bfs#357]
Sdk错误类型

#### 成功

1. cs或ns返回kOK

#### 参数错误

1. 读offset为负，buffer为空
2. seek whence不为SEEK_SET或SEET_CUR
3. open flag不为WR_ONLY或者RD_ONLY
4. open flag为RD_ONLY时write
5. open flag为RD_ONLY时seek
6. open flag为RD_ONLY时sync
7. 以WR_ONLY方式打开已存在文件
8. 非递归方式删除非空目录
9. 非O_TRUNC时打开已经存在的文件
10. 文件已被关闭

#### 元数据不可用

1. ns写元数据失败
2. ns读元数据失败
3. cs close block时失败

#### 不存在

1. 要读的文件不存在
2. 要删的文件或目录不存在
3. cs要读的block不存在

#### 超时

1. sync超时
2. rpc SendRequest返回值不为true
3. 无法得到cs列表
4. cs pending buffer过多
5. cs 未完成的写请求过多
6. cs读失败或写失败
7. cs暂时读写负载过高，AddBlock时拿不到足够的cs

#### 资源不足

1. cs磁盘空间不足，AddBlock时拿不到足够的cs

**Comment by bluebore** [comment]
我觉得分成以下几类更合理，从上到下，严重性依次增加，发生概率依次降低。前4种用户不用重试，前5中，用户自己检查自己问题，不用找我们。
    a. 成功
    b. 操作非法
    c. 无权限
    d. quota不足
    e. 本地网络不可用
    f. 操作超时
    g. 空间不足
    h. 性能过载
    i. 元数据不可用

**Comment by yvxiang** [comment]
暂时还没有把AddBlock时拿不到足够机器情况下，空间不足和负载过高分开
暂时没有更改rpc接口，把rpc错误码暴露出来
