### ISSUE TITLE
optimize safemode

### ISSUE THREAD

**Issue by lylei** [baidu/bfs#402]
现在是写死一个时间，只要到时间就会推出safemode。应该做成自动化的，考虑到cs存活情况和副本情况，能提供服务时自动退出safemode

If cluster has enough alive chunkserver, then it will leave safe mode automatically. Also remove safe mode from block mapping. Use only RecoverMode to control the recover process.

**Comment by yvxiang** [comment]
要不要来个自动进行safemode呢？
