### ISSUE TITLE
recover在chunkserver超时后不能及时取消

### ISSUE THREAD

**Issue by yvxiang** [baidu/bfs#415]
当前recover机制，如果chunkserver的recover速度比较慢，导致nameserver认为pick的block已经超时，重新选择chunkserver进行pick，然而之前的chunkserver对此并不知情，仍然会按之前的顺序进行push，不仅做了无用功，后面的block也因此被堵塞
nameserver在告知chunkserver需要push哪些block时，应该同时告知其超时时间，超时后，chunk server自动放弃push

**Comment by yvxiang** [comment]
#422

**Comment by bluebore** [comment]
这个是不是解决了，可以关了？

**Comment by yvxiang** [comment]
对的
