### ISSUE TITLE
file lost when cs being killed and restart immediately

### ISSUE THREAD

**Issue by lylei** [baidu/bfs#474]
cs在心跳判活时间内kill -9再重启，drop writing block而ns不知道

**Comment by lylei** [comment]
通过block_report时ns检查的方式检查出cs不再汇报的block。
在block_report时，cs汇报block的同时告诉ns自己这次汇报的区间。chunkserver_manager将自己区间内的block和report中的内容比对，此时应检查出cs丢block的情况。因为block id是递增添加的，所以不会出现新写入的block被误判为丢文件。但recover出来的block id会插入在原有block中，时序问题会导致新recover的block被误判为丢文件。
为解决这个问题，在chunkserver_manager里添加一个delta_block_map，记录上次report到现在新receive的block。report比对时，只于原有的block map比对。比对完成后，将新的block merge进原block map

**Comment by bluebore** [comment]
感觉最后提到的解决方案是受时序问题影响的，比如  
1. report1发出，但因nameserver忙，结果返回超时
2. report2发出
3. cs收到一个push的block ，向nameserver报告成功
4. ns收到report1，将delta_block_map merge进blockmap
5. ns收到report2， 误判push的block为丢失
