### ISSUE TITLE
Beginer, build failed.

### ISSUE THREAD

**Issue by xlionet** [baidu/bfs#531]
* Once i tried to build the project by  "./build.sh" ,i always failed ...here is the log information:
```
--2016-10-24 21:00:22--  (try: 5)  http://ftp.yzu.edu.tw/nongnu//libunwind/libunwind-0.99.tar.gz
Connecting to ftp.yzu.edu.tw (ftp.yzu.edu.tw)|140.138.144.170|:80... failed: Connection timed out.
Retrying.
```
What should i do ?

**Comment by lylei** [comment]
Thanks for your issue. It seems like the link is blocked. We are working on finding a new source and make `build.sh` more friendly.
