### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [baidu/bfs#540]
[The variable "`s_quit`"](https://github.com/baidu/bfs/blob/e774ab942f8fec949847bfb667be1f94ab2eb367/src/chunkserver/chunkserver_main.cc#L26 "Update candidate") should [use the data type "`sig_atomic_t`"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.") (instead of "`bool`"), shouldn't it?

**Comment by yvxiang** [comment]
@elfring Thanks for your issue. We have corrected it in #543
