### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by toadzhou** [baidu/bfs#547]
root@debian:~/bfs-master# cat /etc/issue
Debian GNU/Linux 8 \n \l

root@debian:~/bfs-master# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

root@debian:~/bfs-master#./build.sh
....
....
rc/chunkserver/block_manager.cc -o src/chunkserver/block_manager.o
src/version.cc:6:1: error: expected primary-expression before ‘extern’
 extern const char kBuildTime[] = "2016年 10月 27日 星期四 10:33:54 CST";
 ^
src/version.cc: In function ‘void PrintSystemVersion()’:
src/version.cc:14:36: error: ‘kBuildTime’ was not declared in this scope
     std::cout << "Build Time: " << kBuildTime << std::endl;
                                    ^
make: *** [src/version.o] 错误 1
make: *** 正在等待未完成的任务....

**Comment by yvxiang** [comment]
@toadzhou 试了下Debian 8.6，使用build.sh脚本编译是没有问题的，使用的gcc版本为4.9.2，内核版本为3.16.0-4，我修改了一下`build_version.sh`，你可以拉取最新master分支上的代码再试一下

**Comment by toadzhou** [comment]
试了一下问题依旧

**Comment by toadzhou** [comment]
问题已经解决了。
因为网络的原因我一开始只下载了zip包没有clone，但build_version.sh脚本中使用到git log之类的处理。我把.git目录丢进去就解决了。 囧!

**Comment by yvxiang** [comment]
哦哦，了解，不过这确实是个问题，这个我想办法解决下：）
