### ISSUE TITLE
Make error on Mac

### ISSUE THREAD

**Issue by armsword** [baidu/bfs#573]
I'll just skip to the part why bfs doesn't compile on Mac:
修改了很多东西，详细内容不说。只说下可能是影响bfs不能work起来的直接原因：

I remove `libunwind` in `build.sh` since it's not cross platform. Please refer to http://comments.gmane.org/gmane.comp.lib.unwind.devel/2199
在build.sh 里我删除了 libunwind 的安装，原因是 libunwind 不能跨平台，目前无Mac系统支持的版本，详情见此：http://comments.gmane.org/gmane.comp.lib.unwind.devel/2199

The compile error looks like this:
然后，在编译最后阶段，出现的错误为：

```javascript
Undefined symbols for architecture x86_64:
  "_ProfilerStart", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
      sofa::pbrpc::Profiling::DoCpuProfiling(sofa::pbrpc::Profiling::DataType) in libsofa-pbrpc.a(profiling.o)
  "_ProfilerStop", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
  "google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)", referenced from:
      ___cxx_global_var_init in flags.o
      ___cxx_global_var_init.4 in flags.o
      ___cxx_global_var_init.7 in flags.o
      ___cxx_global_var_init.13 in flags.o
      ___cxx_global_var_init.18 in flags.o
      ___cxx_global_var_init.21 in flags.o
      ___cxx_global_var_init.24 in flags.o
      ...
  "google::ParseCommandLineFlags(int*, char***, bool)", referenced from:
      _main in nameserver_main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nameserver] Error 1
make: *** Waiting for unfinished jobs....
```

The program calls `ProfilerStart ` and `ProfilerStop ` and it depends on `perftools` and that leads to the link error.
发现应该是调用 ProfilerStart 和 ProfilerStop ，而这个函数应该是依赖于perftools，所以链接失败。

I don't know if you have better solution.
不知道你们有没有其他解决办法，如果有的话，我应该是可以在Mac下编译成功的，当然，我有时间在细看下这个问题，以上也只是本人猜测的直接原因。

The second question:
第二个问题：

There's a function called `atomic_add64 ` in common library, but the arguments passed in are all `volatile int64_t*`. It will not compile by clang. Should it be fixed?
common库的atomic.h文件里有个 atomic_add64 函数，形参为 volatile long* ，但是实际使用的实参都为 volatile int64_t* 类型，这个在clang下编译会报错的，因为类型不一样，这个是不是需要修改下？

**Comment by armsword** [comment]
Sorry，代码格式乱了，重新尝试贴下：
```javascript
Undefined symbols for architecture x86_64:
  "_ProfilerStart", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
      sofa::pbrpc::Profiling::DoCpuProfiling(sofa::pbrpc::Profiling::DataType) in libsofa-pbrpc.a(profiling.o)
  "_ProfilerStop", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
  "google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)", referenced from:
      ___cxx_global_var_init in flags.o
      ___cxx_global_var_init.4 in flags.o
      ___cxx_global_var_init.7 in flags.o
      ___cxx_global_var_init.13 in flags.o
      ___cxx_global_var_init.18 in flags.o
      ___cxx_global_var_init.21 in flags.o
      ___cxx_global_var_init.24 in flags.o
      ...
  "google::ParseCommandLineFlags(int*, char***, bool)", referenced from:
      _main in nameserver_main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nameserver] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by yvxiang** [comment]
第一个问题：看上去是开启了sofa-pbrpc的profiling功能，在编译sofa-pbrpc时注意不要定义`SOFA_PBRPC_PROFILING`这个宏，应该就可以了
第二个问题：感觉需要改一下common库

**Comment by armsword** [comment]
恩，第二个问题，因为那块代码是汇编写的，我不确认使用int64_t类型是不是正确，所以需要你们确认下。

这块我有空再继续试下，感觉应该是可以在Mac下搞定的，当然编译的配置需要重新定义个对应的Mac编译脚本，比如build_mac.sh

**Comment by bluebore** [comment]
第二个需要统一改一下,具体统一到哪个@yvxiang看下

**Comment by yvxiang** [comment]
我觉得应该统一到in64_t，这可以保证绝对是8字节的，long并不一定能保证。https://github.com/baidu/common/pull/54  已改
