### ISSUE TITLE
debian 8.5 bfs_mount  compile problem

### ISSUE THREAD

**Issue by michaelpop007** [baidu/bfs#588]
fuse/bfs_mount.cc:284:89: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int32_t {aka int}’ [-Werror=format=]
             fprintf(stderr, BFS"Write(%s, %ld) for release fail\n", path, mfile->buf_len);
make bfs_mount无法编译过去，出现如上错误，g++ 4.9.2

**Comment by yvxiang** [comment]
#591 fix this problem
