### ISSUE TITLE
build 出错

### ISSUE THREAD

**Issue by askie** [baidu/bfs#674]
........
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/block.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/chunkserver.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/file.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/master_slave.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/metaserver.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/nameserver.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/raft.proto
./thirdparty/bin/protoc --proto_path=./src/proto/ --proto_path=/usr/local/include --cpp_out=./src/proto/ src/proto/status_code.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:5411] Warning: Unused import: "metaserver.proto" imports "nameserver.proto" which is not used.
g++ -std=c++11 -Wall -fPIC -g2 -Werror  -I./src -I./thirdparty/include -I./thirdparty/include -I/include -I/include -I./thirdparty/include -I./thirdparty/include -c src/flags.cc -o src/flags.o
g++ -std=c++11 -Wall -fPIC -g2 -Werror  -I./src -I./thirdparty/include -I./thirdparty/include -I/include -I/include -I./thirdparty/include -I./thirdparty/include -c src/rpc/nameserver_client.cc -o src/rpc/nameserver_client.o
bash build_version.sh
cc1plus: 错误：无法识别的命令行选项“-std=c++11”
cc1plus: 错误：无法识别的命令行选项“-std=c++11”
make: *** [src/rpc/nameserver_client.o] 错误 1
make: *** 正在等待未完成的任务....
make: *** [src/flags.o] 错误 1

系统：centos 6.5

**Comment by yvxiang** [comment]
用的gcc版本是哪个？BFS当前需要编译器支持C++11

**Comment by askie** [comment]
安装c++1后，编译出错：
/usr/bin/ld: cannot find -ltcmalloc_minimal
collect2: 错误：ld 返回 1
make: *** [nameserver] 错误 1
make: *** 正在等待未完成的任务....

**Comment by askie** [comment]
src/stacktrace.cc: In function 'int GetStackTraceWithContext(void**, int, int, const void*)':
src/stacktrace.cc:239:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [stacktrace.lo] 错误 1
+ cd -
/root/tools/bfs/bfs/thirdsrc
+ touch /root/tools/bfs/bfs/.build/gperftools_2_2_1

**Comment by yvxiang** [comment]
看起来是`gperftools`没编过，到`bfs/thirdsrc/gperftools`目录下`make clean && make `一下看看报不报错？

**Comment by askie** [comment]
报错：
src/stacktrace.cc: In function 'int GetStackTraceWithContext(void**, int, int, const void*)':
src/stacktrace.cc:239:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [stacktrace.lo] 错误 1

**Comment by yvxiang** [comment]
这是`gperftools`本身的warning，编译选项开了`-Werror`?

**Comment by yvxiang** [comment]
@askie 现在编译通过了吗？

**Comment by askie** [comment]
依然过不去，我在群里面反馈了，过去一个，再出来一个。
新安装的centos6.5系统。

**Comment by yvxiang** [comment]
现在是哪一步出了问题？
