### ISSUE TITLE
sdk缓存文件信息

### ISSUE THREAD

**Issue by yvxiang** [baidu/bfs#72]
当前client每次打开文件时都需要向nameserver发送GetFileLocation请求，是否有必要做一个缓存，或者一次GetFileLocation时，将邻近文件的信息也发送回来？

**Comment by bluebore** [comment]
缓存需要做，但“临近”的文件，这个不好界定啊

**Comment by linyvxiang** [comment]
或者可以再额外添加一个第三方的缓存（如redis之类），来减轻nameserver的压力
