### ISSUE TITLE
快速上手文档中的一个疑问

### ISSUE THREAD

**Issue by ToWorld** [baidu/bfs#748]
[issue快速上手文档中的一个疑问.docx](https://github.com/baidu/bfs/files/684297/issue.docx)
快速上手文档中的一个疑问
文档链接：https://github.com/baidu/bfs/blob/master/docs/cn/quick_start.md
文档中有那么一行：--bfs_log_limit=1024000 # 总的log限制,超过限制会删除旧的log
我对这一行有疑问: 
我的理解：日志是用来监测系统运行并用于后期错误排查的，那么日志中应该尽量存放可能出错的信息，那么当系统出错的那么一会，日志记录的信息很可能有利于知道系统的错误原因，这样的信息肯定是需要保存下来，而不是删除。但是，系统出错之后，之后日志记录的信息很可能是一些垃圾信息(因为系统已经处于不正常状态)，如果这个时候还是一味的将这些垃圾信息存储在日志中，那么等日志文件很大时，便会将之前的有利于排查错误的信息删除，而保留这些垃圾信息。
所以，我觉得文档中的这句话，或者这个系统在这个方面的处理让我产生疑惑，鉴于我只是一个学生，经验不足，若有不对地方，烦请解惑。
我的解决方案是，对日志系统同时进行监测，若日志系统出现异常时，应该将之前的信息保存下来，最好人工干预。

**Comment by bluebore** [comment]
这个loglimit是用来限制总日至大小的，而我们的日志存储一般都是月级的，并不会丢弃近期的日志。
一般出现异常， 有监控通知人工干预， 所以不会导致错误日志一直打直到超出阈值的。

**Comment by yvxiang** [comment]
非常感谢对BFS的关注~
我感觉单靠日志是不能解决这个问题的，有了日志，同时还需要有对日志的监控，才能在问题出现后的第一时间通知进行人工干预。在实际使用过程中，日志大小一般会设置的足够大，以便在通知人工干预之前不会被滚丢掉

**Comment by yvxiang** [comment]
可以自己搭建一个小的环境玩一玩~

**Comment by ToWorld** [comment]
好嘞

**Comment by bluebore** [comment]
感谢参与
