### ISSUE TITLE
bfs_client can not put file

### ISSUE THREAD

**Issue by yuanych** [baidu/bfs#923]
[root@VM_3_114_centos sandbox]# ./bfs_client put /root/1.txt 1.txt
W 11/26 12:49:02.667716 20391 [src/sdk/file_impl.cc:325] Nameserver AddBlock fail: 1.txt, ret= 1, status= kGetChunkServerError
W 11/26 12:49:12.668391 20391 [src/sdk/file_impl.cc:325] Nameserver AddBlock fail: 1.txt, ret= 1, status= kGetChunkServerError
W 11/26 12:49:22.668949 20391 [src/sdk/file_impl.cc:325] Nameserver AddBlock fail: 1.txt, ret= 1, status= kGetChunkServerError

**Comment by yvxiang** [comment]
How many chunkserver alives in this cluster?
And how many space left in these chunkserver?

**Comment by yuanych** [comment]
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       7.9G  5.8G  1.7G  65% /
/dev/vdb1        99G  9.5G   85G  11% /data

Maybe the space is too small.I mv the chunkserver from /dev/vda1 to /dev/vdb1, the  bfs_client  can put the file . Thanks!
