### ISSUE TITLE
SDK中的bfs_change_replica_num接口无法使用

### ISSUE THREAD

**Issue by FrankCh-en** [baidu/bfs#928]
BFS编译安装成功以后，将生成的libbfs_c.so 拷贝至/usr/local/lib 目录下，在调用bfs_c.h中定义的接口时，bfs_change_replica_num(bfs_fs_t* fs, const char* path, const char* replica_num)接口无法使用，提示找不到定义。其他接口均可成功调用。有没有解决方案呢？

**Comment by FrankCh-en** [comment]
AttributeError: ./libbfs_c.so: undefined symbol: bfs_change_replica_num

**Comment by apady** [comment]
问题已解决！原因：bfs_c.cc 成员函数命名与 bfs_c.h bfs_change_replica_num()命名不一致。将bfs_c.c中的bfs_change_bfs_fslica_num() 改为bfs_change_replica_num()即可。
已提交 Pull requests。

**Comment by apady** [comment]
为什么bfs_change_bfs_fslica_num()的实现被注释了？
位置 src/sdk/fs_imply.cc

<img width="848" alt="image" src="https://user-images.githubusercontent.com/45413681/49289420-b0bea000-f4de-11e8-88c5-93ae7585adf0.png">

**Comment by apady** [comment]
问题已解决
