### ISSUE TITLE
libunwind-0.99编译失败

### ISSUE THREAD

**Issue by Huoke** [baidu/bfs#937]
../include/dwarf.h:318:5: error: unknown type name 'pthread_mutex_t'
     pthread_mutex_t lock;

**Comment by Huoke** [comment]
In file included from ../include/dwarf_i.h:9:0,
                 from dwarf/global.c:26:
../include/dwarf.h:318:5: error: unknown type name 'pthread_mutex_t'
     pthread_mutex_t lock;
     ^~~~~~~~~~~~~~~
Makefile:2768: recipe for target 'dwarf/global.lo' failed
make[2]: *** [dwarf/global.lo] Error 1
make[2]: Leaving directory '/mnt/f/bfs/thirdsrc/libunwind-0.99/src'
Makefile:1182: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/f/bfs/thirdsrc/libunwind-0.99/src'
Makefile:362: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by yvxiang** [comment]
`pthread_mutex_t`是系统自带的，看起来跟环境有关系，手动加上这个依赖吧

**Comment by Huoke** [comment]
这个问题出现在我的windows10系统，在win10的appStare中下载的Ubantu下编译出现这个问题，现在我在libunwind-0.99源码的 include/dwarf.h文件中添加了pthread.h 可以编译通过了。
多谢！

**Comment by Huoke** [comment]
问题解决
